= Common terms in software

Before we start coding something, we have to have a common understanding of the most common terms in software that we can apply across any language, while this is not a complete list, this is the basis for any software code. Most of the code bases that you will see out there will be structured using this concepts.

== Data type

A representation of certain value, for example, age is an integer number, name is a combination of characters, pi is a floating number

== Common data types

|===
|Type  |Example
|Integer | 1,2,10
|Character | a,b,c
|String(sometimes known as a string of characters) | hello world, goodbye
|===

== Constant

A named fixed value, for example pi = 3.14, i = √–1

== Variable

A named variable value, for example age=30

== Method

A named series of instructions, for example:

[%linenums,source]
calculateArea
  lenght=2
  width=3
  result=length*width
  return result

== Comment

A piece of text within a code base that it's not used by the computer, and it's only used by any person reading the code

[%linenums,source]
//Method that calculates the area
methodName
  // provided lenght
  x=2
  // provided width
  y=3
  // calculated result
  z=x*y
  return z

Note: I personally do not like to include comments in my code as a comment does not need to be updated once someone updates a comment plus it's always going to be better to understand what the line of code does than a comment, as a comment is just a representation of what the author of the line of code tries to represent, but it might not be what the software is actually doing.

That being said, depending on certain situations, you won't be able to write a code that it's self-explanatory due to certain limitations (specially certain technologies which are very restrictive) so use it wisely.

== Class

A self-contained named code that contains properties (constants or variables) and/or methods

[%linenums,source]
----
class Human
  int age
  string name
  BankAccount bankAccount

  presentYourself
    print "hello my name is" + name + " and I'm " + age + " old"
----

== Constructor

A method that only purpose it's to be able to create an instance of a class

[%linenums,source]
----
class Human
  int humanAge
  string humanName
  BankAccount humanBankAccount

  Human(age, name)
    humanAge=age
    humanName=name

  Human(age, name, bankAccount)
    humanAge=age
    humanName=name
    humanBankAccount=bankAccount

class BankAccount
  float balance

  BankAccount(initialBalance)
    balance=initialBalance
----

Notice that this class contains 2 constructors, that means that if we want to create a human instance, we need to have the age and the name, but we might not need the bank account, as not everyone has a bank account

== Object

An instance of a class

[%linenums,source]
----
damianWhenHeWasYoung = new Human(15,'Damian')

damianBankAccount = new BankAccount(0)
damianNow = new Human(30,'Damian', damianBankAccount)
----

Notice that we can create an instance of the previous example of the class with a bank account or without it

== Conditions
As it's name implies, is a condition that has to be met to execute a certain piece of code

[%linenums,source]
----
 if age>21 then
   print "You are an adult"
 else
   print "You are not an adult yet"
----

== Loop
A block of code that will execute while the initial condition is meet

[%linenums,source]
while age<21
  print "You are not allowed as you are not an adult yet, come back later"

== DRY
Do not repeat yourself, a very important (if not the most important) yet sometimes ignored software principle, the main idea is that you should not repeat your intention in the code as this will create a lot of problems in the long run, several techniques can be applied such as making a code more generic so that common pieces of code can live together and different parts of the code can live in other parts of the project

== KISS
Keep it short and simple. Usually in software engineering, it's very common to see "over-engineered" projects, that are more complicated that it should be, in general the rule is that do not create things that you will need

== Thread
A thread refers to the number of paths of execution, when you code a software that can have multiple threads, it means that it can be executed at the same time.

A CPU nowadays contains multiple core units that have a number of thread executors, the ability for the CPU to process multiple threads at the same time will depend greatly on the amount of threads executors it has.

Multi threading is very useful in situations when some parts of the software have to wait for any reason while other parts of the software can continue working.

== Global variables
These variables have the broadest context possible in the software that you are building. While they can be useful in some places, they bring a great risk as they can be manipulated from any part of the software at any given point in time. The higher the scope of a piece of software like a variable or a method has, the higher is the chance that you will have to use other tools to reduce the ability to manipulate it.

== Immutability
A current state of something cannot change, like a function, method, variable, etc. The more you have the ability to change something already defined in software, the better it has to be handled, specially if it can be referenced in multiple places.

When you have a software that you want to run multiple threads as it support multiple executions of certain pieces of your program at the same time, the higher are the chances that you want to use immutability as you might want to control that only a single part of the program alters this output at a time for a better control.

A way to work with immutability is that you create new instances of the same software rather than to alter the state, in that sense, you only have one state at all point in a software which reduces the risk of altering the values in multiple places when you do not want to.